ALTER TABLE "auth_sessions" ADD COLUMN "last_seen_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "audit_logs" ALTER COLUMN "entity_id" SET DATA TYPE VARCHAR(80);

ALTER TABLE "audit_logs" ADD COLUMN "request_id" VARCHAR(64);
